# -*- coding: utf-8 -*-
"""malaria_druglikes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1grd5EK6G5tsEqxnRHgdwikbfVK4Jbrh-
"""

#import needeed libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#read the smiles csv
druglikes = pd.read_csv('Antimalaria.csv')
druglikes.head()

#install rdkit
!pip install rdkit-pypi

from rdkit import Chem
from rdkit.Chem import Descriptors

# Convert SMILES to RDKit Mol objects
druglikes['Mol'] = druglikes['SMILES'].apply(Chem.MolFromSmiles)

# Remove rows with None in the 'Mol' column
druglikes_valid = druglikes.dropna(subset=['Mol']).copy()

# Calculate properties
druglikes_valid['MolWt'] = druglikes_valid['Mol'].apply(Descriptors.MolWt)
druglikes_valid['LogP'] = druglikes_valid['Mol'].apply(Descriptors.MolLogP)
druglikes_valid['HDonors'] = druglikes_valid['Mol'].apply(Descriptors.NumHDonors)
druglikes_valid['HAcceptors'] = druglikes_valid['Mol'].apply(Descriptors.NumHAcceptors)

display(druglikes_valid.head())

#apply lipinski rule of five
def lipinski_ok(row):
    return (
        row['MolWt'] < 500 and
        row['LogP'] < 5 and
        row['HDonors'] < 5 and
        row['HAcceptors'] < 10
    )

druglikes_valid['DrugLike'] = druglikes_valid.apply(lipinski_ok, axis=1)

display(druglikes_valid.head())

#display results
druglikes_valid[['Compound', 'MolWt', 'LogP', 'HDonors', 'HAcceptors', 'DrugLike']]

#saving as csv
druglikes.to_csv("malaria_druglikes.csv", index=False)

#Saving the result to computer
from google.colab import files
files.download("malaria_druglikes.csv")